language: csharp
mono:
 - latest
solution: src/MyMediaLite-nogui.sln
install:
  - pwd
  - nuget restore src/MyMediaLite-nogui.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/MyMediaLite-nogui.sln
  - make data/ml-100k/u.data
  - pwd
  - ls -R /home/travis/build/kman0
  - tar czf /home/travis/build/kman0/MML.tar.gz /home/travis/build/kman0/MyMediaLite
  - curl --upload-file /home/travis/build/kman0/MML.tar.gz https://transfer.sh/mml.tar.gz
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Tests/bin/Release/Tests.dll
  
